# Generated by Django 3.2.3 on 2022-06-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_testing_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcine',
            name='amount',
        ),
    ]
