# Generated by Django 3.2.3 on 2022-06-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_medcine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcine',
            name='Main_name',
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medcine',
            name='slug',
        ),
    ]
