# Generated by Django 3.2.3 on 2022-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing_API',
        ),
        migrations.AddField(
            model_name='roshetta',
            name='image_01',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='roshetta',
            name='image_02',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
