# Generated by Django 3.2.3 on 2022-07-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Question_01',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Question_02',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Question_03',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
