# Generated by Django 3.2.3 on 2022-07-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20220701_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Question_01',
            new_name='Are_you_deaf',
        ),
    ]
