# Generated by Django 3.2.3 on 2022-07-03 11:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220703_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Currentcomplains',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Angina', 'Angina'), ('Fating fits', 'Fating fits'), ('Hyper tension', 'Hyper tension'), ('Coronary disease', 'Coronary disease'), ('Diabetes', 'Diabetes'), ('Stoke', 'Stoke'), ('Any cardiac operatione', 'Any cardiac operation'), ('Have faced a heart attack', 'Have faced a heart attack'), ('Any chronic disease ', 'Any chronic disease ')], max_length=134),
        ),
        migrations.AddField(
            model_name='profile',
            name='Do_you_have_family_member_faced_early_or_sudden_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Do_you_have_family_member_with_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Do_your_parents_suffer_from_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Do_you_suffer_from',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Angina', 'Angina'), ('Fating fits', 'Fating fits'), ('Hyper tension', 'Hyper tension'), ('Coronary disease', 'Coronary disease'), ('Diabetes', 'Diabetes'), ('Stoke', 'Stoke'), ('Any cardiac operatione', 'Any cardiac operation'), ('Have faced a heart attack', 'Have faced a heart attack'), ('Any chronic disease ', 'Any chronic disease ')], max_length=134),
        ),
    ]
